version: '2'
services:
  dbflowserver-app:
    image: dbflowserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      # - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbflowserver-postgresql:5432/dbFlowServer
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8091:8091
  dbflowserver-postgresql:
    extends:
      file: postgresql.yml
      service: dbflowserver-postgresql
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
